# Generated by Django 2.1 on 2018-12-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0002_auto_20181002_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
    ]
