# Generated by Django 2.1 on 2018-12-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0003_discussion_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='username',
        ),
    ]
