# Generated by Django 2.1 on 2018-12-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0004_remove_comments_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='creator',
        ),
    ]
