# Generated by Django 2.1 on 2018-12-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0006_discussion_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='author',
            field=models.CharField(max_length=15),
        ),
    ]
