# Generated by Django 2.1 on 2018-12-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0007_auto_20181208_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='author',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
