# Generated by Django 2.1 on 2018-12-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0010_auto_20181208_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='author',
            field=models.CharField(max_length=15),
        ),
    ]
