# Generated by Django 2.1 on 2018-12-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0011_auto_20181208_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='username',
            field=models.CharField(default='author', max_length=15),
            preserve_default=False,
        ),
    ]
